#!/bin/bash
#
# OpenOffice startup script - v1.0
#
# Created by Karoly Molnar <kmolnar@eseri.com>
#
# Copyright (c) 1996-2010 Free Open Source Solutions Inc.
# All Rights Reserved
#
# Free Open Source Solutions Inc. owns and reserves all rights, title,
# and interest in and to this software in both machine and human
# readable forms.
#

case "$1" in
    start)
        /usr/bin/soffice -headless -nofirststartwizard -accept="socket,host=localhost,port=8100;urp;StarOffice.Service" 1>/dev/null 2>&1
        ;;
    stop)
        killall soffice.bin 1>/dev/null 2>&1
        ;;
esac

exit 0
