#!/bin/bash
#
# In case the default user menu has changed this script copies the new menu to all users - v1.1
#
# Created by Karoly Molnar <kmolnar@eseri.com>
#
# Copyright (c) 1996-2010 Eseri (Free Open Source Solutions Inc.)
# All Rights Reserved
#
# Free Open Source Solutions Inc. owns and reserves all rights, title,
# and interest in and to this software in both machine and human
# readable forms.
#

for inFile in $(find /home/ -maxdepth 1 -mindepth 1 -type d -print); do
	cp /var/lib/eseriman/templates/desktop/.config/menus/applications.menu.professional $inFile/.config/menus/applications.menu
done

exit 0
