#!/bin/bash
#
# Save actual fail counter values of the vz beancounters to the temporary DB - v1.0
#
# Created by Karoly Molnar <kmolnar@eseri.com>
#
# Copyright (c) 1996-2010 Free Open Source Solutions Inc.
# All Rights Reserved
#
# Free Open Source Solutions Inc. owns and reserves all rights, title,
# and interest in and to this software in both machine and human
# readable forms.
#

su -l -s /bin/bash -c '/usr/local/lib/nagios/plugins/check_openvz -r' nagios

exit $?
