#! /bin/bash
#
# NX and Kerberos V integration
#
# This script is responsible for deleting the Kerberos ticket - v1.0
#
# Created by Karoly Molnar <kmolnar@eseri.com>
#
# Copyright (c) 1996-2010 Eseri (Free Open Source Solutions Inc.)
# All Rights Reserved
#
# Free Open Source Solutions Inc. owns and reserves all rights, title,
# and interest in and to this software in both machine and human
# readable forms.
#

/usr/local/share/eseri/EseriLog "$USER - Suspend"

exit 0
