#!/bin/bash
#
# NX and Kerberos V integration
#
# This script is responsible for setting up the user's cron jobs and also sets the nagios total procs limit - v1.1
#
# Created by Karoly Molnar <kmolnar@eseri.com>
# Modified by Nimesh Jethwa <njethwa@cirruscomputing.com>
#
# Copyright (c) 1996-2015 Eseri (Free Open Source Solutions Inc.)
# All Rights Reserved
#
# Free Open Source Solutions Inc. owns and reserves all rights, title,
# and interest in and to this software in both machine and human
# readable forms.
#

crontab /usr/local/share/eseri/eseriUserCrontab

sudo /var/lib/eseriman/bin/eseriConfigureNagiosProcsLimit &

exit 0
