#!/bin/sh
#
# DSPAM database cleanup - v1.0
#
# Created by Karoly Molnar <kmolnar@eseri.com>
#
# Copyright (c) 1996-2010 Free Open Source Solutions Inc.
# All Rights Reserved
#
# Free Open Source Solutions Inc. owns and reserves all rights, title,
# and interest in and to this software in both machine and human
# readable forms.
#

dspam_clean -s -p -u >/dev/null 2>&1
vacuumdb -f -h pgsql.[-DOMAIN-] -U dspam -t dspam_signature_data dspam >/dev/null 2>&1
vacuumdb -f -h pgsql.[-DOMAIN-] -U dspam -t dspam_token_data dspam >/dev/null 2>&1

exit 0
