#!/usr/bin/perl
#
# cirrus_del_cloud v1.1
#
# Modified by Nimesh Jethwa <njethwa@cirruscomputing.com>
#
# Copyright (c) 1996-2014 Eseri (Free Open Source Solutions Inc.)
# All Rights Reserved
#
# Free Open Source Solutions Inc. owns and reserves all rights, title,
# and interest in and to this software in both machine and human
# readable forms.
#

use Git;
use Tie::File;
use Regexp::Common qw(net);

if ($#ARGV != 4){
	print "Usage: cirrus_del_cloud orgname publicip bridgename archive_folder template_folder\n";
	print "E.g: ./cirrus_del_cloud test 1.2.3.4 brTEST /root/deployA1067/archive /root/deployA1067/template\n";
	exit 1;
}

my $ORGNAME = $ARGV[0];
my $PUBLICIP = $ARGV[1];
my $BRNAME = $ARGV[2];
my $ARCHIVE_FOLDER = $ARGV[3];
my $TEMPLATE_FOLDER = $ARGV[4];

#debug print "del org $ORGNAME $PUBLICIP $BRNAME\n";

unless ($PUBLICIP =~ m/^$RE{net}{IPv4}$/){
	print "Public IP must be an IPv4 address\n";
#	exit 1; let's continue anyhow -- RWL 2013-12
}
unless ($BRNAME =~ m/^br[A-Z0-9]+$/){
	print "Bridge name must be in form brNAME\n";
#	exit 1; let's continue anyhow -- RWL 2013-12
}
unless (-e "/etc/sysconfig/network-scripts/ifcfg-$BRNAME"){
	print "Bridge does not appear to exist\n";
#	exit 1; let's continue anyhow -- RWL 2013-12
}

system("$ARCHIVE_FOLDER/cirrus_del_bridge_route", "$BRNAME");


my $git = Git->repository("/etc/shorewall");
foreach my $file ("interfaces", "masq", "policy", "routestopped", "rules", "zones", "proxyarp"){
	tie my @contents, 'Tie::File', "/etc/shorewall/$file";
	@contents = grep { ! /^INCLUDE \/etc\/shorewall\/orgs.local\/$ORGNAME\// } @contents;
	untie @contents;
	$git->command("add", "/etc/shorewall/$file");
}
$git->command("rm", "-rf", "/etc/shorewall/orgs.local/$ORGNAME");
system("service", "shorewall", "restart");
if ($? != 0){
	#Huh ... not sure what the best thing to do here is, so do a commit with a warning message
	$git->command("commit", "-m", "Invalid config after removing $ORGNAME");
	exit 1;
}
else{
	$git->command("commit", "-m", "$ORGNAME removed, networking nominal");
	# in case there are files remaining such as rules.bak 
	# that prevent the directory from being deleted
	system("rm -rf /etc/shorewall/orgs.local/$ORGNAME");
	exit 0;
}
