#!/bin/bash
#
# Call dspam on hera for training - v1.0
#
# Created by Karoly Molnar <kmolnar@eseri.com>
#
# Copyright (c) 1996-2010 Eseri (Free Open Source Solutions Inc.)
# All Rights Reserved
#
# Free Open Source Solutions Inc. owns and reserves all rights, title,
# and interest in and to this software in both machine and human
# readable forms.
#

# Check parameters
[ $# -ne "1" ] && exit 1
[ "$1" != "spam" -a "$1" != "innocent" ] && exit 1

# Call dspam for training
cat /dev/stdin | ssh root@hera.[-DOMAIN-] "/usr/bin/dspam --client --user $SUDO_USER@$(hostname -d) --class=$1 --source=error"

exit 0
