#! /bin/bash
#
# NX and Kerberos V integration
#
# This script is responsible for setting the KRB5CCNAME environment variable
# in either ~/.profile or ~/.bashrc - v1.0
#
# Created by Karoly Molnar <kmolnar@eseri.com>
#
# Copyright (c) 1996-2010 Free Open Source Solutions Inc.
# All Rights Reserved
#
# Free Open Source Solutions Inc. owns and reserves all rights, title,
# and interest in and to this software in both machine and human
# readable forms.
#

/usr/local/share/eseri/EseriLog "$USER - Login"

# Remove Kerberos 5 environment variable export
sed -i '/KRB5CCNAME/d' $HOME/.profile

# Export the Kerberos 5 environment variable
echo "export KRB5CCNAME=/tmp/`ls -t /tmp/ | grep krb5cc_${UID}_ | sed '2,$ d'`" >> $HOME/.profile

exit 0
