#!/bin/bash

#
#       Nagios-Shorewall-Plugin
#       checks whether or not the shorewall is running
#       Copyright (C) 2008  Wolfgang Hotwagner
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


SHOREWALL="/sbin/shorewall"

STATELINE=`$SHOREWALL status | grep State:`
STATE=`echo $STATELINE | awk '{print $1}' | cut -d ':' -f 2`

case "$STATE" in
        Started)
                        echo "$STATELINE"
                        exit 0
                        ;;
        Stopped)
                        echo "$STATELINE"
                        exit 2
                        ;;
        *)
                        echo "$STATELINE"
                        exit 3
                        ;;
esac
